### ISSUE TITLE
GCN template is broken

### ISSUE THREAD

**Issue by lpsinger** [growth-astro/growth-too-marshal#27]
```
127.0.0.1 - - [24/Apr/2019 16:51:36] "GET /event/2018-11-01T22:22:47/localization/bayestar.fits.gz/plan/telescope/DECam/gz_greedy_1_1_integrated_50_90/gcn HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lpsinger/src/growth-too-marshal/growth/too/views.py", line 334, in create_gcn_template
    authors=authors)
  File "/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/lpsinger/src/growth-too-marshal/growth/too/templates/gcn.jinja2", line 14, in top-level template code
    corresponding to ~{{ "%.1f"|format(plan.get_probability(localization)) }}%
  File "/Users/lpsinger/src/growth-too-marshal/growth/too/models.py", line 732, in get_probability
    return localization.flat_2d[ipix].sum()
jinja2.exceptions.UndefinedError: 'localization' is undefined
```

**Comment by mcoughlin** [comment]
This was fixed yesterday.
