### ISSUE TITLE
Scheduling is failing with "KeyError: 'mindiff'"

### ISSUE THREAD

**Issue by lpsinger** [growth-astro/growth-too-marshal#52]
In production, scheduling is failing with the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_celeryext/app.py", line 79, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/growth/too/tasks/tiles.py", line 400, in tile
    mindiff=plan_args['mindiff'])
KeyError: 'mindiff'
```

**Comment by lpsinger** [comment]
The database had to be rebuilt, that's all.
